CREATE TABLE Role (
    ID_Roli SERIAL PRIMARY KEY,
    Nazwa_Roli VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE Uzytkownicy (
    ID_Uzytkownika SERIAL PRIMARY KEY,
    Login VARCHAR(50) NOT NULL UNIQUE,
    Haslo VARCHAR(255) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Data_Rejestracji TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_Roli INTEGER NOT NULL,
    CONSTRAINT fk_uzytkownicy_role FOREIGN KEY (ID_Roli) REFERENCES Role(ID_Roli)
);